In [77]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [132]:
df = pd.read_csv('DelayedFlights.csv')

In [133]:
df.shape

(1936758, 30)

In [134]:
df.describe()

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,FlightNum,...,Distance,TaxiIn,TaxiOut,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,1.936758e+06,1936758.0,1.936758e+06,1.936758e+06,1.936758e+06,1.936758e+06,1.936758e+06,1.929648e+06,1.936758e+06,1.936758e+06,...,1.936758e+06,1.929648e+06,1.936303e+06,1.936758e+06,1.936758e+06,1.247488e+06,1.247488e+06,1.247488e+06,1.247488e+06,1.247488e+06
mean,3.341651e+06,2008.0,6.111106e+00,1.575347e+01,3.984827e+00,1.518534e+03,1.467473e+03,1.610141e+03,1.634225e+03,2.184263e+03,...,7.656862e+02,6.812975e+00,1.823220e+01,3.268348e-04,4.003598e-03,1.917940e+01,3.703571e+00,1.502164e+01,9.013714e-02,2.529647e+01
std,2.066065e+06,0.0,3.482546e+00,8.776272e+00,1.995966e+00,4.504853e+02,4.247668e+02,5.481781e+02,4.646347e+02,1.944702e+03,...,5.744797e+02,5.273595e+00,1.433853e+01,1.807562e-02,6.314722e-02,4.354621e+01,2.149290e+01,3.383305e+01,2.022714e+00,4.205486e+01
min,0.000000e+00,2008.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,...,1.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.517452e+06,2008.0,3.000000e+00,8.000000e+00,2.000000e+00,1.203000e+03,1.135000e+03,1.316000e+03,1.325000e+03,6.100000e+02,...,3.380000e+02,4.000000e+00,1.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,3.242558e+06,2008.0,6.000000e+00,1.600000e+01,4.000000e+00,1.545000e+03,1.510000e+03,1.715000e+03,1.705000e+03,1.543000e+03,...,6.060000e+02,6.000000e+00,1.400000e+01,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,8.000000e+00
75%,4.972467e+06,2008.0,9.000000e+00,2.300000e+01,6.000000e+00,1.900000e+03,1.815000e+03,2.030000e+03,2.014000e+03,3.422000e+03,...,9.980000e+02,8.000000e+00,2.100000e+01,0.000000e+00,0.000000e+00,2.100000e+01,0.000000e+00,1.500000e+01,0.000000e+00,3.300000e+01
max,7.009727e+06,2008.0,1.200000e+01,3.100000e+01,7.000000e+00,2.400000e+03,2.359000e+03,2.400000e+03,2.400000e+03,9.742000e+03,...,4.962000e+03,2.400000e+02,4.220000e+02,1.000000e+00,1.000000e+00,2.436000e+03,1.352000e+03,1.357000e+03,3.920000e+02,1.316000e+03

In [135]:
# Name: Description
# Year: 2008
# Month: 1-12
# DayofMonth: 1-31
# DayOfWeek: 1 (Monday) - 7 (Sunday)
# DepTime: actual departure time (local, hhmm)
# CRSDepTime: scheduled departure time (local, hhmm)
# ArrTime: actual arrival time (local, hhmm)
# CRSArrTime: scheduled arrival time (local, hhmm)
# UniqueCarrier: unique carrier code
# FlightNum: flight number
# TailNum: plane tail number
# ActualElapsedTime: in minutes
# CRSElapsedTime: in minutes
# AirTime: in minutes
# ArrDelay: arrival delay, in minutes
# DepDelay: departure delay, in minutes
# Origin: origin IATA airport code
# Dest: destination IATA airport code
# Distance: in miles
# TaxiIn: taxi in time, in minutes
# TaxiOut: taxi out time in minutes
# Cancelled: was the flight cancelled?
# CancellationCode: reason for cancellation (A = carrier, B = weather, C = NAS, D = security)
# Diverted: 1 = yes, 0 = no
# CarrierDelay: in minutes
# WeatherDelay: in minutes
# NASDelay: in minutes
# SecurityDelay: in minutes
# LateAircraftDelay: in minutes

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936758 entries, 0 to 1936757
Data columns (total 30 columns):
Unnamed: 0           int64
Year                 int64
Month                int64
DayofMonth           int64
DayOfWeek            int64
DepTime              float64
CRSDepTime           int64
ArrTime              float64
CRSArrTime           int64
UniqueCarrier        object
FlightNum            int64
TailNum              object
ActualElapsedTime    float64
CRSElapsedTime       float64
AirTime              float64
ArrDelay             float64
DepDelay             float64
Origin               object
Dest                 object
Distance             int64
TaxiIn               float64
TaxiOut              float64
Cancelled            int64
CancellationCode     object
Diverted             int64
CarrierDelay         float64
WeatherDelay         float64
NASDelay             float64
SecurityDelay        float64
LateAircraftDelay    float64
dtypes: float64(14), int64(11), object(5)
memory usage: 443.3+ MB

In [137]:
df.head()

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,...,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2,2008,1,3,4,628.0,620,804.0,750,WN,...,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN
3,4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,...,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,...,4.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN

In [138]:
df = df[['Month', 'DayofMonth', 'DayOfWeek','FlightNum','CRSDepTime', 'DepDelay', 'TaxiOut', 'Distance','CRSArrTime','ArrDelay']]

In [139]:
df.shape

(1936758, 10)

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936758 entries, 0 to 1936757
Data columns (total 10 columns):
Month         int64
DayofMonth    int64
DayOfWeek     int64
FlightNum     int64
CRSDepTime    int64
DepDelay      float64
TaxiOut       float64
Distance      int64
CRSArrTime    int64
ArrDelay      float64
dtypes: float64(3), int64(7)
memory usage: 147.8 MB

In [141]:
df.dropna()

,Month,DayofMonth,DayOfWeek,FlightNum,CRSDepTime,DepDelay,TaxiOut,Distance,CRSArrTime,ArrDelay
0,1,3,4,335,1955,8.0,8.0,810,2225,-14.0
1,1,3,4,3231,735,19.0,10.0,810,1000,2.0
2,1,3,4,448,620,8.0,17.0,515,750,14.0
3,1,3,4,3920,1755,34.0,10.0,515,1925,34.0
4,1,3,4,378,1915,25.0,10.0,688,2110,11.0
5,1,3,4,509,1830,67.0,7.0,1591,1940,57.0
6,1,3,4,100,700,6.0,19.0,828,915,1.0
7,1,3,4,1333,1510,94.0,8.0,828,1725,80.0
8,1,3,4,2272,1020,9.0,9.0,162,1010,11.0
9,1,3,4,675,1425,27.0,8.0,1489,1625,15.0
10,1,3,4,1144,745,9.0,16.0,1489,955,-15.0
11,1,3,4,4,1255,28.0,9.0,838,1510,16.0
12,1,3,4,54,1325,51.0,5.0,220,1435,37.0
13,1,3,4,623,1625,32.0,5.0,220,1735,19.0
14,1,3,4,717,1840,20.0,5.0,220,1950,6.0
15,1,3,4,1244,1030,9.0,5.0,220,1140,-7.0
16,1,3,4,2553,1455,25.0,7.0,220,1605,14.0
17,1,3,4,188,1255,87.0,6.0,1093,1610,47.0
18,1,3,4,1754,1925,29.0,7.0,1093,2235,4.0
19,1,3,4,362,1945,82.0,7.0,972,2230,64.0
20,1,3,4,1397,1300,12.0,7.0,972,1550,-4.0
21,1,3,4,3398,1430,19.0,6.0,972,1720,-5.0
22,1,3,4,3480,1555,39.0,6.0,972,1845,14.0
23,1,3,4,422,1650,82.0,11.0,765,1815,72.0
24,1,3,4,1837,1105,22.0,5.0,765,1230,5.0
25,1,3,4,2871,1355,29.0,6.0,765,1520,11.0
26,1,3,4,1056,1230,56.0,5.0,1052,1530,29.0
27,1,3,4,2175,1725,24.0,8.0,1052,2030,-11.0
28,1,3,4,3319,720,6.0,8.0,1052,1020,-22.0
29,1,3,4,3667,640,6.0,9.0,1101,955,-26.0
...,...,...,...,...,...,...,...,...,...,...
1936728,12,13,6,1451,1440,32.0,16.0,950,1743,3.0
1936729,12,13,6,1457,705,73.0,24.0,1076,1016,63.0
1936730,12,13,6,1458,1056,40.0,19.0,1076,1356,31.0
1936731,12,13,6,1459,1100,8.0,18.0,1076,1424,-28.0
1936732,12,13,6,1470,1336,67.0,13.0,874,1652,63.0
1936733,12,13,6,1476,1355,27.0,17.0,1589,1929,38.0
1936734,12,13,6,1477,1646,36.0,28.0,2486,2027,26.0
1936735,12,13,6,1491,710,9.0,15.0,1183,949,-11.0
1936736,12,13,6,1503,735,18.0,33.0,1011,1043,11.0
1936737,12,13,6,1504,1125,7.0,14.0,1011,1404,4.0
1936738,12,13,6,1512,1126,33.0,112.0,1589,1703,125.0
1936739,12,13,6,1530,1045,15.0,12.0,692,1347,3.0
1936740,12,13,6,1538,1150,10.0,15.0,2172,1921,3.0
1936741,12,13,6,1542,934,21.0,20.0,859,1155,20.0
1936742,12,13,6,1547,1048,61.0,16.0,545,1235,76.0
1936743,12,13,6,1550,1000,53.0,14.0,432,1141,37.0
1936744,12,13,6,1553,1210,41.0,7.0,516,1400,34.0
1936745,12,13,6,1554,950,35.0,41.0,516,1130,48.0
1936746,12,13,6,1563,1355,34.0,14.0,906,1729,20.0
1936747,12,13,6,1586,1954,12.0,33.0,291,2109,24.0
1936748,12,13,6,1609,1221,33.0,13.0,432,1359,21.0
1936749,12,13,6,1611,1500,28.0,29.0,507,1642,38.0
1936750,12,13,6,1612,1522,9.0,14.0,692,1823,-1.0
1936751,12,13,6,1616,830,51.0,21.0,545,1008,64.0
1936752,12,13,6,1620,1520,32.0,7.0,151,1718,17.0
1936753,12,13,6,1621,1220,30.0,18.0,906,1552,25.0
1936754,12,13,6,1631,600,57.0,34.0,481,749,75.0
1936755,12,13,6,1631,847,80.0,32.0,689,1010,99.0
1936756,12,13,6,1639,1240,11.0,13.0,533,1437,9.0
1936757,12,13,6,1641,1103,7.0,11.0,874,1418,-5.0

In [142]:
df.shape

(1936758, 10)

In [143]:
# sns.jointplot(df['DepDelay'],df['DayOfWeek'])
#Rough Visualisation of the graph obtained shows that the majority of delays happen during Fridays, followed by Monday

In [144]:
# sns.jointplot(df['DepDelay'],df['Month'])
#The visualisation below shows that maximum delays happen in december that is during christmas month

In [145]:
for i in range(len(df['ArrDelay'])):
    if((df['ArrDelay'].values)[i]>15.0):
        (df['ArrDelay'].values)[i] = 1.0
    else:
        (df['ArrDelay'].values)[i] = 0.0

In [146]:
print(df['ArrDelay'].values)

[0. 0. 0. ... 1. 0. 0.]

The function written below shows the nuber of tuples which have target values 0 and 1 repectively

In [147]:
count1 = 0
count0 = 0
for i in range(len(df['ArrDelay'])):
    if((df['ArrDelay'].values)[i] == 0.0):
        count0 = count0+1
    else:
        count1 = count1+1
print(count0,count1)

721746 1215012

We can see that the dataset is **SKEWED** with a difference of 493266 tuples.

In [148]:
1215012-721746

493266

The method written down below will help remove the extra tuples with value 1.0, resulting in a balanced dataset

In [149]:
indexes = []
for i in range(len(df['ArrDelay'].values)):
    if((df['ArrDelay'].values)[i] == 1.0):
        indexes.append(i)

In [150]:
new_indexes = (indexes[:493266])

In [151]:
df = df.drop(new_indexes)

In [152]:
count1 = 0
count0 = 0
for i in range(len(df['ArrDelay'])):
    if((df['ArrDelay'].values)[i] == 0.0):
        count0 = count0+1
    else:
        count1 = count1+1
print(count0,count1)

721746 721746

In [165]:
df.shape

(1443492, 10)

In [161]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1443492 entries, 0 to 1936757
Data columns (total 10 columns):
Month         1443492 non-null int64
DayofMonth    1443492 non-null int64
DayOfWeek     1443492 non-null int64
FlightNum     1443492 non-null int64
CRSDepTime    1443492 non-null int64
DepDelay      1443492 non-null float64
TaxiOut       1443037 non-null float64
Distance      1443492 non-null int64
CRSArrTime    1443492 non-null int64
ArrDelay      1443492 non-null float64
dtypes: float64(3), int64(7)
memory usage: 121.1 MB

In [169]:
df = df.dropna()

In [175]:
df.shape

(1443037, 10)

In [176]:
X = df[['Month', 'DayofMonth', 'DayOfWeek','FlightNum','CRSDepTime', 'DepDelay', 'TaxiOut', 'Distance','CRSArrTime',]]
y = df['ArrDelay']

In [177]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=101)

In [178]:
from sklearn.linear_model import LogisticRegression

In [179]:
lr = LogisticRegression()

In [180]:
lr.fit(X_train,y_train)

D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [181]:
pred = lr.predict(X_test)

In [182]:
from sklearn.metrics import classification_report, confusion_matrix

In [183]:
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

         0.0       0.85      0.92      0.89    216008
         1.0       0.91      0.84      0.88    216904

   micro avg       0.88      0.88      0.88    432912
   macro avg       0.88      0.88      0.88    432912
weighted avg       0.88      0.88      0.88    432912

[[198477  17531]
 [ 33947 182957]]